name: Deploy Maven Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-site:
    name: Build site with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Maven Site
        run: mvn -B clean verify site

  deploy-site:
    name: Deploy site to Github Pages
    runs-on: ubuntu-latest
    needs: build-site
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
